### ISSUE TITLE
No react-loadable-chunk-map.json file generated?

### ISSUE THREAD

**Issue by hustcer** [react-loadable/revised#1]
Thanks for your work!
It seems that No `react-loadable-chunk-map.json` file generated? "react-loadable": "^5.5.0" works fine but webpapck 5 not supported, Thanks again.

**Comment by tranvansang** [comment]
@hustcer 

Sorry I didn't notice the issue (somehow, I got unsubscribed from my own repo).
Webpack 5 is currently the supported version.

```
import {ReactLoadablePlugin} from '@react-loadable/revised/webpack'
```

In webpack.config.js

```
		plugins: [
			new ReactLoadablePlugin({
				filename: '../react-loadable.json',
			}),
```

If you use `webpack-dev-middleware`, must specify `writeToDisk` option.

```
webpackDevMiddleware(compiler, {writeToDisk: true})
```

Otherwise, you have to pull the file from outputFileSystem.

```
(req, res, next) => {
// some code
  const jsonContent = res.locals.webpack.devMiddleware.outputFileSystem.readFileSync(absPath, 'utf8')
// some code
}
```

**Comment by tranvansang** [comment]
I close this issue due to inactivity. Feel free to re-open it.
