### ISSUE TITLE
Alternative for Loadable.Map

### ISSUE THREAD

**Issue by rishu605** [react-loadable/revised#4]
We had Loadable.Map in react-loadable but there is no alternative for that in this package.

I was using Loadable.Map to create a LoadableVisibility component as follows:
```
function LoadableVisibilityMap(opts) {
  if (IntersectionObserver) {
    return createLoadableVisibilityComponent([opts], {
      Loadable: Loadable.Map,
      preloadFunc: 'preload',
      LoadingComponent: opts.loading,
    });
  }
  return Loadable.Map(opts);
}
```

Now, the Loadable.Map function is not present in the code of this package. Is there any alternative for this in the revised package ?

**Comment by tranvansang** [comment]
I am not sure what your function does.

The purpose of `Loadable.Map` is to resolve an arbitrary promise (or list of promises) before rendering.
This can be achieved with this revised package, but with an undocumented API via the `opts.render` property of the first parameter `opts` of the `loadable(opts)` function.

```javascript
const LoadableComponent = loadable({
  async loader() {
    const Component = (await import('./MyLazyComponent')).default
    const props = await loadSomeAwaitProps()
    return {Component, props}
  },
  render({Component, props}, clientProps) {
    return <Component {...props} {...clientProps}/>
    // this function should return some react node because it will be rendered in the <LoadableCompoent {...clientProps}/> tree
    // props is what resolved in loader()
    // clientProps is what passed when rendering with <LoadableComponent {...clientProps}/>
  }
})
```

**Comment by tranvansang** [comment]
github doc has been updated. the mentioned API is now documented
