### ISSUE TITLE
mountedRef.current and loadState.promise race condition

### ISSUE THREAD

**Issue by StaRenn** [react-loadable/revised#5]
Hi, i've discovered some kind of a race condition bug

Im testing on dev server and in my case `await loadState.promise` executes before `mountedRef.current = true` in useEffect, so state doesn't update because component thinks that its not mounted, and shows infinite loading, changing useEffect to useLayoutEffect fixes problem for me, but im not sure if thats the reason of the problem, probably you can reproduce it by changing `await loadState.promise` with `await Promise.resolve()` could you please look into it?

**Comment by tranvansang** [comment]
Can you provide more information?

Where did `loadState.promise` and `mountedRef` come from?

**Comment by StaRenn** [comment]
https://github.com/react-loadable/revised/blob/master/src/index.tsx

useEffect on line 127
await loadState.promise line 136

**Comment by tranvansang** [comment]
What is your react version?

**Comment by StaRenn** [comment]
18.2.0

**Comment by tranvansang** [comment]
I got the bug. Let me rolling out a fix PR. Can you test it by replacing the module file in node_modules?

**Comment by StaRenn** [comment]
Yeah, but i'll be home only in 2 hours

**Comment by tranvansang** [comment]
can you check?

https://github.com/react-loadable/revised/pull/6

**Comment by StaRenn** [comment]
That fixed the problem

**Comment by tranvansang** [comment]
released v1.4.1
